zhanglab/psamm

- .travis.yml
- psamm/command.py
- psamm/database.py
- psamm/datasource/native.py
- psamm/datasource/sbml.py
- psamm/expression/affine.py
- psamm/fastcore.py
- psamm/fluxanalysis.py
- psamm/formula.py
- psamm/lpsolver/cplex.py
- psamm/lpsolver/generic.py
- psamm/lpsolver/lp.py
- psamm/lpsolver/qsoptex.py
- psamm/massconsistency.py
- psamm/reaction.py
- psamm/tests/test_affine_expression.py
- psamm/tests/test_boolean_expression.py
- psamm/tests/test_database.py
- psamm/tests/test_formula.py
- psamm/tests/test_kegg.py
- psamm/tests/test_massconsistency.py
- psamm/tests/test_misc.py
- psamm/tests/test_modelseed.py
- psamm/tests/test_reaction.py
- psamm/tests/test_sbml.py
- psamm/tests/test_yaml.py
- setup.py
- tox.ini
Adds support for Python3 while keeping compatibility with Python2 by using the six module.
> Python3 support through six module

- docs/api.rst
- docs/commands.rst
- docs/fluxcoupling.rst
- docs/references.rst
- psamm/command.py
- psamm/fluxcoupling.py
- psamm/tests/test_fluxcoupling.py
Implement flux coupling analysis as the module `fluxcoupling`. A command is added (`fluxcoupling`) to run flux coupling analysis from the command line.
> Flux coupling

- psamm/commands/excelexport.py
- psamm/commands/tableexport.py
- psamm/tests/test_command.py
- setup.py
- tox.ini
This implements a new function that can output the information contained within a model as tab based tables. Contains function for reactions, compounds, medium, and limits. 
Needs work for implementing Excel based workbook export
> Tab based export

- psamm/commands/sbmlexport.py
- psamm/datasource/sbml.py
Export gene association strings to SBML file using COBRA notes.
> Added in export of gene logic strings to psamm-model sbmlexport

- docs/tutorial.rst
Updated tutorial materials to be reflective of new PSAMM 0.19 version.
> Tutorial 0.19 update

- psamm/commands/gapfill.py
> Let the user specify the compounds to unblock in gapfill

- .travis.yml
- docs/install.rst
- psamm/lpsolver/generic.py
- psamm/lpsolver/glpk.py
- psamm/tests/test_command.py
- psamm/tests/test_fastcore.py
- tox.ini
Adds support for the open source (GPL3) LP solver GLPK. Uses the GLPK interface in https://github.com/biosustain/swiglpk. There are still some issues getting `swiglpk` to install correctly on all platforms. The GLPK solver interface currently does not advertise MILP support (in `generic`). The support for MILP problems is in the code but the solver does not seem to respect the integer constraints properly.
Fixes #9.
> GLPK solver (WIP)

- psamm/datasource/native.py
- psamm/tests/test_yaml.py
Using extracelluar compartment as the default compartment in medium if user don't provide one.
> Default compartment

- docs/commands.rst
- psamm/commands/genedelete.py
- psamm/tests/test_command.py
- setup.py
Add gene deletion command and related documentation. This is work based on pull request #45 with some further modifications and squashes on the commit.
> Add gene deletion command

- psamm/util.py
Add repr() method for FrozenOrderedSet.
> util: add repr for class FrozenOrderedSet

- docs/api/balancecheck.rst
- psamm/balancecheck.py
- psamm/commands/chargecheck.py
- psamm/commands/formulacheck.py
- psamm/tests/test_balancecheck.py
Move code from chargecheck and formulacheck commands into a new
balancecheck module.
> Add balancecheck module and test cases

- psamm/command.py
- psamm/commands/excelexport.py
- psamm/commands/tableexport.py
- psamm/datasource/sbml.py
- psamm/fluxanalysis.py
- psamm/metabolicmodel.py
- psamm/reaction.py
- psamm/tests/test_command.py
Fix various unicode format problems, and add test cases for command with unicode as compound IDs
> Fix various unicode format errors

- psamm/datasource/native.py
> fix a typo in native module

- psamm/lpsolver/cplex.py
> cplex: add version check before calling set_offset() method

- psamm/commands/randomsparse.py
- psamm/randomsparse.py
Recover the output layout for randomsparse to the old style.
> Fix output problem for randomsparse command

- psamm/datasource/native.py
- psamm/tests/test_yaml.py
> native: Made it so the 'fixed' key is recognized in limits

- psamm/datasource/native.py
https://github.com/zhanglab/psamm/issues/87
> native: new function to make finding file format more straightforward

- psamm/command.py
- psamm/datasource/context.py
- psamm/datasource/native.py
- psamm/tests/test_balancecheck.py
- psamm/tests/test_command.py
- psamm/tests/test_fastgapfill.py
- psamm/tests/test_randomsparse.py
- psamm/tests/test_yaml.py
https://github.com/zhanglab/psamm/issues/80
> native: NativeModel can take long strings, dicts, or open files as model

- psamm/commands/sbmlexport.py
- psamm/datasource/sbml.py
continuation of https://github.com/zhanglab/psamm/pull/97
> sbml: writer now uses NativeModel instead of MetabolicModel

- psamm/datasource/native.py
https://github.com/zhanglab/psamm/issues/124
> native: psamm-model correctly imports decimal values (not as float)

- psamm/lpsolver/cplex.py
- psamm/lpsolver/glpk.py
- psamm/lpsolver/gurobi.py
> cplex, gurobi, glpk: fix bounds that aren't float

- docs/commands.rst
- docs/references.rst
- psamm/fluxanalysis.py
Add reference to paper where _internal loops_ are defined.
> docs: Add reference for internal loops

- docs/tutorial.rst
> tutorial: Updated tutorial for latest version of PSAMM

- psamm/datasource/native.py
- psamm/datasource/sbml.py
- psamm/tests/test_yaml.py
Export user-defined properties on reactions and compounds in the SBML XHTML-based notes section.
> Sbml export custom notes

- psamm/command.py
- psamm/commands/fastgapfill.py
- psamm/commands/fba.py
- psamm/commands/fluxcheck.py
- psamm/commands/fva.py
- psamm/commands/randomsparse.py
- psamm/commands/robustness.py
- psamm/tests/test_command.py
Add `LoopRemovalMixin` for `Command`. Generates standard `--loop-removal` option on `Command`.
> Loop removal option

- psamm/lpsolver/cplex.py
- psamm/lpsolver/generic.py
- psamm/lpsolver/glpk.py
- psamm/lpsolver/gurobi.py
- psamm/lpsolver/lp.py
- psamm/lpsolver/qsoptex.py
Add standard way of adjusting tolerances on problem.
> LP tolerances

- psamm/gapfill.py
The `gapfill` command is made more robust by automatically adjusting the integrality tolerance based on the epsilon and emitting a warning if the integrality tolerance would be too low for the solver.
> Gapfill flux threshold

- psamm/commands/gapfill.py
After GapFind, show number of blocked compounds found and show
compound IDs along with compound names. If compounds to unblock
are specified with `--compound` but without compartment, assume the
default model compartment.
> gapfill: Improve input parsing and output of result

- psamm/command.py
- psamm/commands/fba.py
- psamm/commands/fluxcheck.py
- psamm/commands/fluxcoupling.py
- psamm/commands/fva.py
- psamm/commands/genedelete.py
- psamm/commands/randomsparse.py
- psamm/commands/robustness.py
- psamm/fluxanalysis.py
- psamm/tests/test_command.py
Provide error message in flux-based analyses when the problem is infeasible and a forced reaction flux in the problem is the likely cause.
> Provide better error message when flux balance problem is infeasible

- docs/commands.rst
- psamm/commands/sbmlexport.py
- psamm/datasource/sbml.py
- psamm/tests/test_command.py
> sbmlexport: user can optionally specify output file

- psamm/commands/fastgapfill.py
- psamm/fastgapfill.py
Reduce amount of unnecessary output produces by the `fastgapfill` command and change the table output to the same format as `gapfill` produces.
> Fastgapfill output

- docs/commands.rst
- psamm/commands/duplicatescheck.py
- psamm/tests/test_command.py
- setup.py
> Duplicates check

- psamm/datasource/sbml.py
- psamm/metabolicmodel.py
- psamm/tests/test_fastgapfill.py
- psamm/util.py
- Ensure that IDs generated from exchange/medium files are unique
- Ensure that IDs for reactions added for gap filling are unique
> Create unique IDs for exchange/transport reactions

- psamm/datasource/native.py
- psamm/tests/test_datasource_native.py
Implement methods for converting `CompartmentEntry` to YAML dictionary representation and writing an iterable of entries to a file.
> native: Allow writing compartments in ModelWriter

- psamm/reaction.py
- psamm/tests/test_command.py
- psamm/tests/test_datasource_native.py
- psamm/tests/test_datasource_reaction.py
- psamm/tests/test_reaction.py
Remove superfluous characters in reaction strings.
> Reaction format

- psamm/datasource/sbml.py
Transfer flux bounds specified by FBCv2 to the model created by `create_model()`. Add comments clarifying that `FluxBoundEntry` is only used for FBCv1 bounds because of the more complicated specification that was used at the time. FBCv2 bounds are converted directly to reaction properties.
> sbml: Properly parse FBCv2 limits when creating model

- setup.py
Uses ini syntax for defining entry points in `setup.py`. This allows any entry point to define additional dependencies.
> setup.py: Make excelexport entry point depend on xlsxwriter

- docs/api/moma.rst
- docs/references.rst
- psamm/lpsolver/lp.py
- psamm/moma.py
- psamm/tests/test_moma.py
First commit fixes some issues when working with quadratic expressions in the LP solver interface.
Continuation of #191 and #172.
> MOMA module

- docs/commands.rst
- docs/references.rst
- psamm/commands/genedelete.py
- psamm/tests/test_command.py
Added MOMA functionality inside the genedelete command. This update also include updates to the docs, references, and tests for the module.
> MOMA in genedelete command

- docs/commands.rst
- docs/references.rst
- psamm/commands/primarypairs.py
- psamm/findprimarypairs.py
- psamm/mapmaker.py
- psamm/tests/test_command.py
- psamm/tests/test_findprimarypairs.py
- psamm/tests/test_mapmaker.py
- setup.py
Add `primarypairs` command and related modules `findprimarypairs` and `mapmaker`.
> Add primarypairs command

- docs/install.rst
- docs/tutorial/curation.rst
- docs/tutorial/import_export.rst
tutorial update to include gapfill and fastgapfill. Also updates section related to new model import
with psamm-import.
> Tutorial v0.31 update
