zhanglab/psamm

docs/faq.rst
docs/index.rst
docs/install.rst

The install instructions are changed to more clearly highlight the procedure for installing psamm into a Virtualenv. The commands are presented in the natural order, which should help someone scanning the document. The use of a Virtualenv is not just presented as an option but as a recommendation.
A FAQ entry is added to specifically address a common Cplex install error.

Improve install docs and add FAQ to documentation

---

docs/commands.rst
psamm/commands/fba.py
psamm/commands/robustness.py

This removes the option `--no-tfba` from the `fba` command and replaces it with the option `--loop-removal` which takes as parameter either "none", "tfba" or "l1min". The default is set to "none". The "tfba" option applies thermodynamic constraints and the "l1min" performs an L1 flux minimization after the standard FBA.

Add option --loop-mode to select loop constraints

---

docs/commands.rst
psamm/commands/fluxcheck.py
psamm/commands/fva.py

Using thermodynamic constraints has the advantage of automatically removing internal flux loops. However, this comes at a price of being much more time-consuming; requiring an MILP-capable LP solver; and sometimes resulting in problems that the solver is unable to solve. This PR disables thermodynamic constraints for the commands `fva` and `fluxcheck` by default and also changes the `--no-tfba` option to `--tfba`. The option is still available to enable thermodynamic constraints when the user deems it worthwhile.
The thermodynamic constraints are disabled by default for `fba` and `robustness` in #26.

Do not apply thermodynamic constraints by default

---

psamm/command.py

Displays a warning for each compound that is found in a reaction in the model but not defined in the list of compounds.

command: Warn about compounds that are not defined in the model

---

psamm/commands/randomsparse.py
psamm/commands/robustness.py

Change `--reaction` option to `--objective` in `robustness` and `randomsparse` as suggested in #30. The commands `fba` and `fva` can also take a reaction to use as the objective but for these commands the reaction is given as a positional parameter. For this reason only the `robustness` and `randomsparse` are changed.

Change --reaction to --objective in commands

---

docs/file_format.rst
psamm/command.py
psamm/datasource/native.py

Fixes #37. This allows for the medium definition to be split into logical subdivisions in separate files.

Combine the media in model.yaml into one medium

---

psamm/fastcore.py
psamm/fluxanalysis.py
psamm/fluxcoupling.py
psamm/gapfill.py
psamm/lpsolver/cplex.py
psamm/lpsolver/generic.py
psamm/lpsolver/gurobi.py
psamm/lpsolver/lp.py
psamm/lpsolver/qsoptex.py
psamm/massconsistency.py
psamm/tests/test_cplex.py
psamm/tests/test_lpsolver_lp.py

Changes the LP solver interface to allow quadratic expressions to be constructed and set as the objective. Support is implemented in `cplex`. The method `set_linear_objective` was renamed to `set_objective` since the same method is used to set both types of objectives (or mixed objectives).

Allow quadratic objectives in LP problems

---

psamm/commands/chargecheck.py

When psamm output charge check result, instead of printing the reaction object, just printing the reaction IDs.

chargecheck: Fix printing reaction IDs

---

psamm/formula.py
psamm/tests/test_formula.py

Creates a metaclass for `Atom` so that standard elements can be accessed as properties on the `Atom` class, e.g. `Atom.H` instead of `Atom('H')`. This is preferred since typos in the element symbol will more easily be caught this way. Non-standard element symbols can still be created using the normal constructor, e.g. `Atom('X')`. In addition, `Atom` instances are cached by symbol so that trying to construct a new instance with an existing symbol will return the cached (singleton) object.

Make Atoms singletons and simplify access

---

psamm/lpsolver/cplex.py

Calling `get_num_binary()` on the Cplex instance appears to cause a segfault in some rare cases. We work around this by avoiding the call on the first solve. This may not work around the segfault if the `solve()` method is called multiple times but at least it works for problems that are only solved once.
The problem reset is only needed if a problem is modified after the first solve, so it should be safe to skip the first part of `_reset_problem_type()` if the problem has not been solved before.

cplex: Work around segfault in Cplex library

---

psamm/command.py
psamm/commands/excelexport.py
psamm/commands/fastgapfill.py
psamm/commands/fba.py
psamm/commands/fluxcheck.py
psamm/commands/fluxcoupling.py
psamm/commands/fva.py
psamm/commands/genedelete.py
psamm/commands/masscheck.py
psamm/commands/randomsparse.py
psamm/commands/robustness.py
psamm/tests/test_command.py

I am not sure if providing a string to the function `fail()` is OK, but it seems like that if it is a True value, and it is not a tuple, python would call sys.exc_info() to get the exception info.
Also, I don't know how to test the `argument_error()` and `fail()` using the existing structure in `test_command.py`, I want to construct a Command instance, but it's an abstract base class. To test these two functions, I don't want to run any actual command either.

Command error methods

---

psamm/commands/gapfill.py

Add option on `gapfill` command to adjust epsilon parameter (threshold for considering a flux value zero or non-zero). In the second commit, an error message is added when the GapFind or GapFill procedure fails, explaining to the user that the epsilon parameter can be adjusted as a possible solution to the failure. Currently `CommandError` is used to report the error which, in addition, generates a usage message which is not appropriate for this kind of error. This should be changed when #74 is fixed.

Gapfill epsilon option

---

psamm/commands/excelexport.py
psamm/commands/tableexport.py
psamm/datasource/native.py
psamm/tests/test_command.py

`NativeModel.get_default_flux_limit()` returns 1000 instead of `None` if no default value found in the model definition. Also change two commands and test cases related to this change.

Default flux limit

---

psamm/commands/tableexport.py
psamm/tests/test_command.py

add an extra column for `tableexport` module to indicate whether a certain reaction or compound is in the model definition.

Extra col tableexport

---

psamm/massconsistency.py
psamm/tests/test_massconsistency.py

Simplifies the LP problems for checking mass consistency while still guaranteeing that zero mass compounds are ignored.

massconsistency: Do not return values for zeromass compounds

---

psamm/database.py
psamm/tests/test_database.py

Based on first commit in #108. Extended tests to check that ordering is preserved. @spikeliu can you tell me if this looks good?

database: Retain compound order

---

psamm/fastcore.py
psamm/fluxanalysis.py
psamm/fluxcoupling.py
psamm/gapfill.py
psamm/lpsolver/lp.py
psamm/massconsistency.py

This removes the need for using magic strings to identify a subset of variables. Improves the ability to provide abstractions on LP problems without the risk of namespace collisions.

lp: Add variable namespaces

---

psamm/datasource/native.py

This changes the YAML model parser so that compounds with no compartment specified will be placed in the default compartment. If not specified in `model.yaml` the default compartment will be `c`. This means that a `None` compartment is no longer created if a reaction does not specify a compartment.
Questions:
- Is it ever desirable to have `None` compartments?
- Is is ok to always convert unspecified compartments to the default compartment?
- How does this interact with psamm-import?

Add default_compartment option in model.yaml

---

psamm/datasource/sbml.py
psamm/expression/boolean.py
psamm/tests/test_boolean_expression.py

Provides access to the root term (`And`, `Or`, `Variable` or `bool`) of the boolean expression. Previously the private `_root` member of `Expression` was accessed when writing SBML files because there was no public interface for obtaining this.

boolean: Provide access to root of term tree

---

psamm/gapfill.py

Fixes a possible problem in `gapfind` when the solver result is not exactly zero.

gapfill: Fix check for blocked compounds

---

psamm/lpsolver/generic.py
psamm/lpsolver/glpk.py
psamm/tests/test_gapfill.py

GLPK is marked as having integer (MILP) support in the generic interface.
Also changes the test cases for GapFind/GapFill to work with GLPK. GLPK is not able to handle a wide range between the epsilon and big-M parameter so epsilon was increased for this test.

Activate GLPK MILP support

---

psamm/commands/fastgapfill.py

The `fastgapfill` command did not construct the induced model correctly when a subset was specified. The induced model was missing all model reactions that were not part of the subset. This resulted in an error when FBA was applied to the induced model.

fastgapfill: optional command subset has been fixed

---

psamm/datasource/native.py
psamm/tests/test_yaml.py

Correctly parse special float values in YAML to `Decimal` representation.

native: Parse special float values (inf, nan)

---

psamm/commands/formulacheck.py

Fixes a bug where the `formulabalance` command did not correctly check against the set of excluded reactions.

formulabalance: Fix exclude reactions

---

docs/commands.rst
docs/tutorial.rst
psamm/command.py
psamm/commands/fba.py
psamm/commands/fva.py
psamm/commands/genedelete.py
psamm/commands/randomsparse.py
psamm/commands/robustness.py

Add `ObjectiveMixin` for `Command`. Adds standardized option to override the biomass reaction as the objective. Changes a few commands to use `--objective` as option instead of a positional argument.

Objective mixin

---

psamm/commands/gapfill.py

Previously a value of 1000 was hardcoded.

Use default flux value as v_max for GapFind/GapFill

---

psamm/commands/gapfill.py

List all model reactions with an indication that they are already in the model. Then, list any added or reversed reactions alphabetically by ID. This makes the output more similar to the `fastgapfill` output.

gapfill: Improve output by listing all reactions

---

psamm/commands/gapfill.py
psamm/gapfill.py
psamm/tests/test_gapfill.py

Changes procedure so that epsilon indicates the flux threshold instead of the compound production threshold. In addition, instead of trying to make irreversible reactions reversible, the procedure will more generally try to expand the flux bounds of reactions that are limited to a narrower range than [-v_max; v_max].

gapfill: Reformulate GapFind/GapFill

---

psamm/lpsolver/cplex.py
psamm/lpsolver/glpk.py
psamm/lpsolver/gurobi.py
psamm/lpsolver/lp.py
psamm/lpsolver/qsoptex.py
psamm/tests/test_lpsolver_lp.py

Changes the tolerances on solvers to be exposed through an
object that provides access to both the current value and the
minimum/maximum values for each tolerance setting.

lp: Allow access to tolerances through property with min/max

---

psamm/commands/gapfill.py
psamm/gapfill.py

Continuation of #148. Adds penalty options for gapfill command similar to fastgapfill. Penalties apply to both adding reactions (database reactions) and modifying flux bounds of existing reactions.

Gapfill penalty

---

psamm/datasource/entry.py
psamm/datasource/kegg.py
psamm/datasource/modelseed.py
psamm/datasource/native.py
psamm/datasource/sbml.py
psamm/tests/test_kegg.py
psamm/tests/test_yaml.py
psamm/util.py

Adds abstract and concrete model entries in `psamm.datasource.entry` and changes the data from the `sbml`, `modelseed`, `native` and `kegg` modules to conform to the abstract classes.

Add abstract and concrete model entries

---

psamm/datasource/native.py
psamm/tests/test_datasource_native.py

The model writing code from psamm-import is copied and adapted as `ModelWriter` in the `native` module. Currently only adds methods for writing YAML reaction and compound files.

Write native model

---

docs/commands.rst

Add documentation for new `gapcheck` command. Adjust documentation for old `gapfill` command which was changed to only doing gap-filling.

docs: Update for gapcheck command

---

psamm/commands/tableexport.py
psamm/tests/test_command.py

Standardize table output fields in tableexport as JSON-except-mostly-unquoted-string. Strings are only quoted if they contain tabs or newlines.

tableexport: Quote problematic fields

---

psamm/command.py
psamm/commands/excelexport.py
psamm/commands/search.py
psamm/datasource/context.py
psamm/datasource/native.py
psamm/datasource/sbml.py
psamm/tests/test_command.py

Run tests directly using the `Command` and a `NativeModel` parsed from dict. This removes the step from all command tests that go through the `main()` function (this should be tested separately) and removes string parsing of `NativeModel`. The command tests are faster and more specific as a result.
First two commits fix various bugs uncovered by the change to the tests.

Simplify tests for commands

---

.travis.yml
setup.py
tox.ini

Run tests with Python 3.5/3.6 and mark these versions as supported in `setup.py`.

Support Python 3.5/3.6

---

psamm/lpsolver/cplex.py
tox.ini

The parameter `solutiontarget` has been deprecated. The new name for this parameter is `optimalitytarget`.
Tox now runs tests on CPLEX with Python 3.5 since that is the only Python 3 version that is supported by CPLEX 12.7.

Fix support for CPLEX 12.7

---

psamm/command.py

When running a command with the --help option, the description of the command is shown. This description is based on the docstring of the Command subclass representing the running command. However, the formatting of the original docstring is not preserved. For example, the tableexport command contains a docstring with a list formatted with bullet points indentation and whitespace. In the output all newlines are converted to single spaces. The output should use the original formatting insert.
Fixed the problem by using RawDescriptionHelpFormatter as formatter_class. Description of the argument is below.
> Passing RawDescriptionHelpFormatter as formatter_class= indicates that description and epilog are already correctly formatted and should not be line-wrapped:
Documentation: …

Fixed --help newline styling

---

docs/api/datasource_context.rst
docs/api/datasource_entry.rst
docs/api/lpsolver_cplex.rst
docs/api/lpsolver_glpk.rst
docs/api/util.rst
docs/conf.py
psamm/lpsolver/glpk.py

Adds entries for modules in the API documentation that were previously left out.
Some fixes were applied to docstrings in the `glpk` module where the docstrings erroneously referred to `gurobi`.

Add missing API documentation

---

docs/file_format.rst
psamm/datasource/entry.py
psamm/datasource/native.py
psamm/tests/test_command.py
psamm/tests/test_datasource_entry.py
psamm/tests/test_datasource_native.py

Compartments are specified in `model.yaml`, for example:
``` yaml
name: Example model
biomass: Biomass_reaction
compartments:
- id: p
name: Periplasm
adjacent_to: [c, e]
- id: c
name: Cytosol
adjacent_to: p
- id: e
name: Extracellular space
compounds:
```
Notice that the adjacency can be specified as a single compartment or a list of compartments. Note that it is sufficient to specify that `p` is adjacent to `e`. It is then inferred that `e` is adjacent to `p` so it is optional to specify both directions of adjacency.
The compartment information is parsed and represented as `CompartmentEntry` in `NativeModel`. The compartment boundaries are also made available by `NativeModel` and will be used to create correct transport reactions for gap-filling in another pull request.

Allow compartments to be specified in model.yaml

---

docs/commands.rst
psamm/commands/gapfill.py
psamm/gapfill.py
psamm/tests/test_gapfill.py

- Show weight of proposed changes in output. This is similar to the output of the `fastgapfill` command and makes it easier to determine why a particular solution was found.
- Add option `--no-implicit-sinks` to disable implicit sinks in the `gapfill` command.
- Add option `--allow-bounds-expansion` to allow GapFill to propose expansion of flux bounds as a possible solution. This also includes making irreversible reactions reversible. This is disabled by default in line with the original GapFill algorithm.

Add options to gapfill command

---

psamm/datasource/context.py

Changes the string representation of FileMark to only include line and column numbers if those are specified. If not specified, the string representation will simply list the path.

context: Do not write question marks in FileMark string

---

psamm/lpsolver/cplex.py
psamm/lpsolver/glpk.py
psamm/lpsolver/lp.py
psamm/tests/test_lpsolver_generic.py

- Fixes issues in `cplex` and `glpk` where an expression supplied as objective containing non-float numbers results in an exception.
- Fixes general expression evaluation in `Result` base class in `lp` module to be able to handle expressions with non-float numbers.

Fix issues with non-float numbers provided to solver

---

psamm/datasource/context.py
psamm/fastgapfill.py
psamm/metabolicmodel.py
psamm/tests/test_fastgapfill.py
psamm/tests/test_metabolicmodel.py

Use compartment boundary information to decide which artificial transport reactions to generate for gap-filling. For consistency, also add database reactions based on the compartments specified in the model (i.e. only add database reactions that are within model compartments as specified in `model.yaml`). This means that now compartments must be defined when using database reactions for gap-filling.

Use compartment information when gap-filling

---

psamm/lpsolver/lp.py
psamm/tests/test_lpsolver_lp.py

Raise an error when using chained comparisons with an Expression object, e.g. 4 <= x <= 100 where x is an Expression object. This expands to 4 <= x and x <= 100 but the "and" operator cannot be overridden and currently it simply discards the first part of the constraint because the Relation object created from 4 <= x simply evaluates to True. Raising an error seems to be the best way to catch this kind of mistake.
A test was fixed in the first commit because it mistakenly used `assertEqual` to compare expression objects. `assertEqual` cannot be used for Expressions because the equality operator is overridden to construct Relation objects.

lp: Raise error on certain use of Expression/Relation

---

docs/commands.rst
psamm/commands/gapcheck.py
psamm/tests/test_command.py

Adding methods `prodcheck` (production check like GapFind) and `sinkcheck` (check whether excess can be produced through sink) to the `gapcheck` command.
- Production check iterates over all reactions and checks which compounds can be produced. This works like GapFind but is more robust and is reasonably fast (can also be parallelized if needed).
- Sink check iterates over all compounds and tries to maximize the flux through a sink. This is similar to GapFind but always requires an excess of the compound to be produced. This means that compounds are blocked unless they can successfully be synthesized from the medium. Compounds that merely form a loop (e.g. tRNA charging) are not counted as produced.
- Implicit sinks are present for all compounds with these method but an option is added to …

gapcheck: Implement alternative production check

---

docs/file_format.rst
docs/tutorial.rst
psamm/commands/excelexport.py
psamm/commands/tableexport.py
psamm/datasource/native.py
psamm/datasource/sbml.py
psamm/metabolicmodel.py
psamm/tests/test_command.py
psamm/tests/test_datasource_native.py
psamm/tests/test_gapfilling.py
psamm/tests/test_randomsparse.py

Rename the "media" key in the model file to "exchange" reflecting the fact that it specifies both compounds with allowed uptake (the medium) and compounds allowed to exit the model system. Also introduces related changes in `tableexport` and `excelexport` commands.
The old "media" key is still parsed in the model files but is deprecated and a warning is produced if it is present. The "medium" command in `tableexport` still works but the same command can also be run be specifying "exchange".
Documentation on the file format and tutorial is updated with this change.

Rename media to exchange

---

psamm/datasource/sbml.py
psamm/tests/test_datasource_sbml.py

When the `ignore_boundary` option is True, compounds that were marked as boundary compounds are ignored. However, any compartments that existed solely for these compounds were not ignored. With this change the compartment is also ignored and does not produce an entry.

sbml: Ignore boundary compartments

---

psamm/datasource/sbml.py
psamm/tests/test_datasource_sbml.py

The charge property was not made available when accessing the information in the `SpeciesEntry` through the `properties` dictionary. This only happened for SBML level 1-2 files.

sbml: Fix access to charge property

---

psamm/lpsolver/lp.py

Add alternative lookup syntax for namespaces `v[1]` instead of `v(1)`. This works better when keys are tuples: `v[1, 2]` vs. `v((1,2))`. Also implement `__contains__` so the `in` operator can be used instead of `has_variable()`. Add additional documentation on the use of namespaces.

Namespace update

---

psamm/commands/excelexport.py

When excelexport fails due to missing xlsxwriter, include the
pip command line to install the package in the error message.

excelexport: Mention name of Python package in error message

---

psamm/commands/excelexport.py

Fix bug where limits header was overwritten by the first row of
limits and fix writing limits where the default flux limit
applies.

excelexport: Fix writing limits

---

psamm/datasource/sbml.py

Adds constants LESS_EQUAL, GREATER_EQUAL and EQUAL corresponding
to the supported operations of the flux bounds in SBML. Also
adds docstrings for properties.

sbml: Extend FluxBoundObjective with constants

---

psamm/balancecheck.py
psamm/command.py
psamm/commands/chargecheck.py
psamm/commands/console.py
psamm/commands/duplicatescheck.py
psamm/commands/excelexport.py
psamm/commands/fastgapfill.py
psamm/commands/fba.py
psamm/commands/fluxcheck.py
psamm/commands/fva.py
psamm/commands/gapcheck.py
psamm/commands/gapfill.py
psamm/commands/genedelete.py
psamm/commands/masscheck.py
psamm/commands/robustness.py
psamm/commands/search.py
psamm/commands/tableexport.py
psamm/datasource/native.py
psamm/datasource/sbml.py
psamm/gapfilling.py
psamm/randomsparse.py
psamm/tests/test_balancecheck.py
psamm/tests/test_command.py
psamm/tests/test_datasource_native.py
psamm/tests/test_gapfilling.py
psamm/tests/test_randomsparse.py

In `native`, change `NativeModel` so that it works as a store of model data in memory. The model parsing is moved to a new class `ModelReader` which can parse individual model sections (e.g. compounds, reactions) and also create a new `NativeModel` in-memory representation. The `NativeModel` is supplied to commands which means that commands no longer have to manually parse the model using `parse_X()` methods but can instead access the model entries directly.

Split reader part of NativeModel into ModelReader

---

psamm/commands/console.py

Before two models were available from the console. With this
change only `NativeModel` is available. The `MetabolicModel` can be
created using `create_metabolic_model()`. Instructions for doing
this are included in the help message.

console: Simplify by only including one model

---

psamm/command.py
psamm/datasource/sbml.py
psamm/tests/test_command.py
setup.py

Add command `psamm-sbml-model` to run any command directly on an SBML file. Since this is using the `SBMLReader` in `psamm.datasource.sbml` it only supports the standardized SBML format and does not yet support alternative data such as COBRA-specific encodings of objective, flux bounds, gene associations etc. that are common in level 1 and 2 files.

Add command to operate on SBML files directly

---

psamm/gapfilling.py

The functions for adding transport and exchange reactions would
supply the property model.reactions to the function that
generates a unique ID. This function expects a set in order to
do quick lookup but will also work with other collections that
support the `in` operator or even iterators. The performance issue
appeared for large models because model.reactions is not a set but
an iterator. This resulted in the gap-filling functions spending
large amounts of time traversing the same iterator over and over
when creating the extended model. This is fixed by first
creating a set from the iterator and using the set when
trying to generate unique IDs.

gapfilling: Fix performance issue when adding reactions

---

psamm/datasource/entry.py
psamm/datasource/native.py

This makes it easier to work with these objects interactively
and improves error messages in some cases.

native: Provide repr for common classes

---

psamm/datasource/sbml.py
psamm/tests/test_command.py
psamm/tests/test_datasource_sbml.py

It was also considered whether lxml could be used. lxml would have
been able to supply additional information, such as line numbers of
element definitions. However, lxml has compatibility issues with
the way namespaces are handled in the sbml module currently.
The tests that rely on inline XML data were modified. On Python 2.7,
cElementTree only works with a file that reads
bytes. StringIO returns unicode if initialized with a unicode
string. This results in cElementTree failing if a unicode
string is supplied in test cases (or if unicode_literals is set).
Instead use BytesIO with a string explicitly encoded as UTF-8.
This works in all cases.

sbml: Use cElementTree if possible

---

psamm/datasource/sbml.py

This makes error messages and repr output less confusing by making
it clear that these are SBML specific objects.

sbml: Add SBML prefix to entity classes

---

psamm/datasource/sbml.py
psamm/tests/test_datasource_sbml.py

Adds property `xml_annotation` on SBML entries (SBMLSpeciesEntry, SBMLReactionEntry, etc.) which provides access to the annotation `Element` instance.

sbml: Allow access to SBML annotations

---

psamm/datasource/entry.py
psamm/tests/test_datasource_entry.py

Previously, the ID of a model entry could not be modified (by design) even on mutable entries such as `DictCompoundEntry`, `DictReactionEntry`. However, this made it difficult to translate model IDs when this was desired (for example, for removing ID prefixes in SBML models). An ID override parameter is added to the constructor so that a new entry can be created from an existing entry but with a different ID.
Additionally some setters are added to the mutable entries to make modifications easier. Documentation of the mutability and rules for ID are expanded.

Expand ModelEntry with id override and setters

---

psamm/datasource/native.py
psamm/tests/test_datasource_native.py

Add tests for `_OrderedEntrySet` in native module (used for providing access to compound, reaction and compartment entries in `NativeModel`). Add `clear()` and `update()` methods.

native: Add methods + tests for _OrderedEntrySet

---

psamm/command.py
psamm/datasource/entry.py
psamm/datasource/native.py
psamm/datasource/sbml.py
psamm/tests/test_datasource_entry.py
psamm/tests/test_datasource_native.py
psamm/tests/test_datasource_sbml.py

`psamm-import` currently performs many additional model conversions on top of the output of `SBMLReader` to make additional model data available and to fit the model into the native representation. This is an attempt to move this functionality into the `sbml` module so it can be used from the PSAMM API.

Perform additional SBML model conversions

---

psamm/balancecheck.py
psamm/formula.py
psamm/tests/test_formula.py

- Base `Formula` on `Counter` instead of `dict`. This allows some multiset operators to be defined more efficiently. The operators `__and__` and `__sub__` are added.
- Add a `ParseError` exception in the `formula` module and use it to report errors in `Formula.parse()`. The parse exception may contain a span indicating the location of the parse error in the input string. This information is used in `balancecheck` to show better error messages.

Improvements to Formula

---

psamm/commands/gapcheck.py
psamm/fluxanalysis.py
psamm/fluxcoupling.py
psamm/gapfill.py
psamm/lpsolver/cplex.py
psamm/lpsolver/glpk.py
psamm/lpsolver/gurobi.py
psamm/lpsolver/lp.py
psamm/lpsolver/qsoptex.py
psamm/massconsistency.py
psamm/tests/test_lpsolver_cplex.py

Adds the SolverError in the lp module. Exceptions raised from the
solver when solve() is called should inherit from this or should
be wrapped as this to allow callers to handle such conditions
gracefully.
In addition, the SolverError is also raised by solve() when a non-optimal solution is found.
This helps avoid a common bug where the result is not checked and
therefore non-optimal solution values are used as though an optimal
solution was found. Instead the solve() now raises a SolverError
when no optimal solution is found. This makes it impossible to
forget to check the solution in the most common case. In cases
when the exception is not desired the new solve_unchecked() can
be used which has the old behavior.

Forward solver errors and raise error on non-optimal solutions

---

setup.py
tox.ini

Moved xlsxwriter package used in excelexport command to required packages during install. this will allow the package to be automatically installed upon install of PSAMM with pip.

Added xlsxwriter to required packages for install.
